
- name: 'generate kube-proxy cert files'
  local_action: 'shell cfssl gencert -ca=roles/common/files/ca.pem -ca-key=roles/common/files/ca-key.pem -config=roles/common/files/config.json -profile=kubernetes  roles/nodeconfig/files/kube-proxy-csr.json | cfssljson -bare kube-proxy'
  tags:
    - kubeproxy
    - nodeconfig

- name: 'create kubelet folader'
  file:
    path: '/etc/kubernetes/ssl'
    state: directory
  tags:
    - kubeproxy
    - nodeconfig

- name: 'copy kube-proxy-key.pem file'
  copy:
    src: kube-proxy-key.pem
    dest: /etc/kubernetes/ssl/kube-proxy-key.pem
  tags:
    - kubeproxy
    - nodeconfig

- name: 'copy kube-proxy.pem file'
  copy:
    src: kube-proxy.pem
    dest: /etc/kubernetes/ssl/kube-proxy.pem
  tags:
    - kubeproxy
    - nodeconfig

- name: 添加 kube-proxy 在集群中的配置
  shell: 'kubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/ssl/ca.pem --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig=kube-proxy.kubeconfig'
  tags:
    - kubeproxy
    - nodeconfig

- name: 配置  kube-proxy 客户端认证
  shell: 'kubectl config set-credentials kube-proxy --client-certificate=/etc/kubernetes/ssl/kube-proxy.pem --client-key=/etc/kubernetes/ssl/kube-proxy-key.pem --embed-certs=true --kubeconfig=kube-proxy.kubeconfig'
  tags:
    - kubeproxy
    - nodeconfig


- name: 关联context 和集群
  shell: 'kubectl config set-context default --cluster=kubernetes --user=kube-proxy --kubeconfig=kube-proxy.kubeconfig'
  tags:
    - kubeproxy
    - nodeconfig


- name: 关联default context 和集群
  shell: 'kubectl config use-context default --kubeconfig=kube-proxy.kubeconfig'
  tags:
    - kubeproxy
    - nodeconfig

- name: 从远程拷贝回生成的 kube-proxy.kubeconfig
  fetch:
    src: /root/kube-proxy.kubeconfig
    dest: ./kube-proxy.kubeconfig
    flat: yes
  run_once: yes
  tags:
    - kubeproxy
    - nodeconfig
    - fetch
