---
- hosts: k8s
  remote_user: root
  tasks:
    - debug:
        msg: 'start prepare tasks'
  roles:
    - common
    - dockerinstall

- hosts: etcd
  remote_user: root
  tasks:
    - debug:
        msg: 'set up etcd cluster'
  roles:
    - etcdinstall

- hosts: masters
  remote_user: root
  tasks:
    - debug:
        msg: 'start setup masters'
  roles:
    - copybinaries
    - master
    - nodeconfig

- hosts: k8s
  remote_user: root
  tasks:
    - debug:
        msg: 'start setup nodes'
  roles:
    - copybinaries
    - bootstrap
    - nginx
    - node