- name: 'make etcd cert config file'
  local_action:
    module: template
    src: etcd-csr.json.j2
    dest: etcd-csr.json

- name: 'create etcd cert pem files'
  local_action: shell cfssl gencert -ca roles/common/files/ca.pem -ca-key=roles/common/files/ca-key.pem -config=roles/common/files/config.json -profile=kubernetes etcd-csr.json | cfssljson -bare etcd

- name: 'copy etcd key files'
  copy:
    src: "etcd-key.pem"
    dest: '/etc/kubernetes/ssl/etcd-key.pem'

- name: 'set etcd key permission'
  file:
    path: '/etc/kubernetes/ssl/etcd-key.pem'
    mode: '644'

- name: 'copy etcd cert files'
  copy:
    src: "etcd.pem"
    dest: '/etc/kubernetes/ssl/etcd.pem'

- name: 'copy etcd files'
  copy:
    src: "etcd"
    dest: '/usr/bin/etcd'
    mode: '777'
- name: 'copy etcdctl files'
  copy:
    src: "etcdctl"
    dest: '/usr/bin/etcdctl'
    mode: '777'


- name: 'check /opt/etcd folder exsit'
  stat:
    path: /opt/etcd
  register: p
- debug:
    msg: "/opt/etcd exists and is a directory"
  when: p.stat.isdir is defined and p.stat.isdir

- name: 'create etcd data folader'
  file:
    path: '/opt/etcd'
    state: directory
#   when: p.stat.isdir is defined and p.stat.isdir

- name: 'make etcd systemd config file'
  local_action:
    module: template
    src: etcd-service.j2
    dest: "etcd-{{ansible_default_ipv4[\"address\"]}}.service"
  tags: 'temp'

- name: 'copy etcd systemd files'
  copy:
    src: "etcd-{{ansible_default_ipv4[\"address\"]}}.service"
    dest: '/etc/systemd/system/etcd.service'

- name: 'enable etcd service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: etcd
    state: started

