- name: 'create kubelet service file'
  local_action:
    module: template
    src: kubelet.service.j2
    dest: kubelet-{{ansible_default_ipv4['address']}}.service
  tags:
    - kubelet
    - config
    - cni

- name: 'copy kubelet service file'
  copy:
    src: kubelet-{{ansible_default_ipv4['address']}}.service
    dest: /etc/systemd/system/kubelet.service
  # when: stat_result.stat.exists == False
  tags:
    - kubelet
    - cni

- name: 'enable kubelet service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: kubelet
    state: restarted
  tags:
    - kubelet
    - cni