- name: 'check ali docker repo existing'
  stat:
    path: '/etc/yum.repos.d/docker-ce.repo'
  register: stat_result

- name: 'add ali docker repo'
  copy:
    src: 'docker-ce.repo'
    dest: '/etc/yum.repos.d/docker-ce.repo'
  when: stat_result.stat.exists == False

- debug:
    msg: "ali docker repo already exist , ignore copy repo file"
  when: stat_result.stat.exists == True
- name: 'install device-mapper-persistent-data,lvm2'
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - device-mapper-persistent-data
    - lvm2
- name: 'install docker-ce-18.06.0.ce-3.el7'
  command: 'yum install -y --setopt=obsoletes=0 docker-ce-18.06.0.ce-3.el7'
- name: 'create /etc/docker foladers'
  file:
    path: '/etc/docker'
    state: directory
- name: 'copy daemon.json to /etc/docker'
  copy:
    src: 'daemon-3.10.json'
    dest: '/etc/docker/daemon.json'
- name: 'enable and start docker service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: docker
    state: started

    
