- name: 'create kubelet folader'
  file:
    path: '/var/lib/kubelet'
    state: directory
  tags:
    - kubelet
    - masterandnode

- name: 'check kubelet existing'
  stat:
    path: '/usr/local/bin/kubelet'
  register: stat_result
  tags:
    - masterandnode

- name: 'copy kubelet file'
  copy:
    src: kubelet
    dest: /usr/local/bin/kubelet
    mode: '755'
    # mode: u=rwx,g=rx,o=rx
    # mode: u+rw,g-wx,o-rwx
  when: stat_result.stat.exists == False
  tags:
    - kubelet
    - masterandnode

- name: 'create kubelet service file'
  local_action:
    module: template
    src: kubelet.service.j2
    dest: kubelet.service
  tags:
    - kubelet
    - config
    - masterandnode

- name: 'create kubelet config json file'
  local_action:
    module: template
    src: kubelet.config.json.j2
    dest: kubelet.config.json
  tags:
    - kubelet
    - config
    - masterandnode

- name: 'copy kubelet service file'
  copy:
    src: kubelet.service
    dest: /etc/systemd/system/kubelet.service
  when: stat_result.stat.exists == False
  tags:
    - kubelet
    - masterandnode

- name: 'copy kubelet config json file'
  copy:
    src: kubelet.config.json
    dest: /etc/kubernetes/kubelet.config.json
  when: stat_result.stat.exists == False
  tags:
    - kubelet
    - masterandnode

- name: 'Wait 10 seconds for masters api server port 6443 to become open'
  wait_for:
    port: 6443
    host: "{{ hostvars[item]['ansible_ssh_host'] }}"
    delay: 10
    state: drained
  # loop: "{{query('inventory_hostnames', 'masters')}}"
    loop: "{{groups['masters']}}"
  connection: local


- name: 'enable kubelet service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: kubelet
    state: restarted
  tags:
    - kubelet
    - masterandnode

- name: 'ls kubelet certification files '
  shell: 'ls -lt /etc/kubernetes/ssl/kubelet*'
  tags:
    - kubelet
    - nodes


- name: 'copy kube-proxy.kubeconfig to /etc/kubernetes/'
  copy:
    src: kube-proxy.kubeconfig
    dest: /etc/kubernetes/kube-proxy.kubeconfig
  tags:
    - kubeproxy
    - masterandnode

- name: 安装IP set 相关工具
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - ipset
    - ipvsadm
    - conntrack-tools.x86_64
  tags:
    - kubeproxy
    - masterandnode

- name: '生成kube-proxy service文件'
  local_action:
    module: template
    src: 'kube-proxy.config.yaml.j2'
    dest: "kube-proxy.config-{{ansible_default_ipv4['address']}}.yaml"
  tags: 
    - masterandnode
    - config
    - kubeproxy

- name: 'copy kube-proxy.config.yaml'
  copy:
    src: "kube-proxy.config-{{ansible_default_ipv4['address']}}.yaml"
    dest: /etc/kubernetes/kube-proxy.config.yaml
  tags:
    - kubeproxy
    - masterandnode

- name: 'create kube-proxy folader'
  file:
    path: '/var/lib/kube-proxy'
    state: directory
  tags:
    - kubeproxy
    - masterandnode



- name: 'check kube-proxy existing'
  stat:
    path: '/usr/local/bin/kube-proxy'
  register: kube_proxy_result
  tags:
    - kubeproxy
    - masterandnode
    - temp

- name: 'copy kube-proxy file'
  copy:
    src: kube-proxy
    dest: /usr/local/bin/kube-proxy
    mode: '755'
    # mode: u=rwx,g=rx,o=rx
    # mode: u+rw,g-wx,o-rwx
  when: kube_proxy_result.stat.exists == False
  tags:
    - kubeproxy
    - masterandnode
    - temp

- name: 'copy kube-proxy serivce file'
  copy:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    # mode: u=rwx,g=rx,o=rx
    # mode: u+rw,g-wx,o-rwx
  tags:
    - kubeproxy
    - masterandnode
    - temp

- name: 'enable kube-proxy service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: kube-proxy
    state: restarted
  tags:
    - kubeproxy
    - masterandnode
    - temp