

- name: 'create kubelet folader'
  file:
    path: '/var/lib/kubelet'
    state: directory
  tags:
    - kubelet
    - node

# - name: 'check kubelet existing'
#   stat:
#     path: '/usr/local/bin/kubelet'
#   register: stat_result
#   tags:
#     - node

# - name: 'copy kubelet file'
#   copy:
#     src: kubelet
#     dest: /usr/local/bin/kubelet
#     mode: '755'
#     # mode: u=rwx,g=rx,o=rx
#     # mode: u+rw,g-wx,o-rwx
#   when: stat_result.stat.exists == False
#   tags:
#     - kubelet
#     - node

- name: 'create kubelet service file'
  local_action:
    module: template
    src: kubelet.service.j2
    dest: kubelet-{{ansible_default_ipv4['address']}}.service
  tags:
    - kubelet
    - config
    - node

- name: 'copy kubelet service file'
  copy:
    src: kubelet-{{ansible_default_ipv4['address']}}.service
    dest: /etc/systemd/system/kubelet.service
  # when: stat_result.stat.exists == False
  tags:
    - kubelet
    - node

- name: 'create kubelet config json file'
  local_action:
    module: template
    src: kubelet.config.json.j2
    dest: kubelet.config-{{ansible_default_ipv4['address']}}.json
  tags:
    - kubelet
    - config
    - node



- name: 'copy kubelet config json file'
  copy:
    src:  kubelet.config-{{ansible_default_ipv4['address']}}.json
    dest: /etc/kubernetes/kubelet.config.json
  # when: stat_result.stat.exists == False
  tags:
    - kubelet
    - node

- name: 'Wait 10 seconds for masters api server port 6443 to become open'
  debug:
    msg: "{{ hostvars[item]['ansible_ssh_host']}}"
  # loop: "{{query('inventory_hostnames', 'masters')}}"
  loop: "{{groups['masters']}}"
  connection: local


- name: 'Wait 10 seconds for masters api server port 6443 to become open'
  wait_for:
    port: 6443
    host: "{{ hostvars[item]['ansible_ssh_host'] }}"
    delay: 10
    state: drained
  # loop: "{{query('inventory_hostnames', 'masters')}}"
  loop: "{{groups['masters']}}"
  connection: local


- name: 'enable kubelet service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: kubelet
    state: restarted
  tags:
    - kubelet
    - node

# - name: 'ls kubelet certification files '
#   shell: 'ls -lt /etc/kubernetes/ssl/kubelet*'
#   tags:
#     - kubelet
#     - nodes


- name: 'copy kube-proxy.kubeconfig to /etc/kubernetes/'
  copy:
    src: kube-proxy.kubeconfig
    dest: /etc/kubernetes/kube-proxy.kubeconfig
  tags:
    - kubeproxy
    - node

- name: 安装IP set 相关工具
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - ipset
    - ipvsadm
    - conntrack-tools.x86_64
  tags:
    - kubeproxy
    - node

- name: '生成kube-proxy service文件'
  local_action:
    module: template
    src: 'kube-proxy.config.yaml.j2'
    dest: "kube-proxy.config-{{ansible_default_ipv4['address']}}.yaml"
  tags: 
    - node
    - config
    - kubeproxy

- name: 'copy kube-proxy.config.yaml'
  copy:
    src: "kube-proxy.config-{{ansible_default_ipv4['address']}}.yaml"
    dest: /etc/kubernetes/kube-proxy.config.yaml
  tags:
    - kubeproxy
    - node

- name: 'create kube-proxy folader'
  file:
    path: '/var/lib/kube-proxy'
    state: directory
  tags:
    - kubeproxy
    - node

- name: 'copy kube-proxy serivce file'
  copy:
    src: kube-proxy.service
    dest: /etc/systemd/system/kube-proxy.service
    # mode: u=rwx,g=rx,o=rx
    # mode: u+rw,g-wx,o-rwx
  tags:
    - kubeproxy
    - node
    - temp

- name: 'enable kube-proxy service'
  systemd:
    daemon_reload: yes
    enabled: yes
    name: kube-proxy
    state: restarted
  tags:
    - kubeproxy
    - node
    - temp